//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CauHinh
    {
        public string MaCauHinh { get; set; }
        public string nvTenUngDung { get; set; }
        public string nvTenDoanhNghiep { get; set; }
        public string ChucVu { get; set; }
        public string Tenuser { get; set; }
        [DisplayName("User Name")]
        [Required(ErrorMessage = "Lỗi trường file")]
        public string nvUser { get; set; }
        public string nvDiaChi { get; set; }
        public string nvDienThoai { get; set; }
        public string nvFax { get; set; }
        public string nvEmail { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Lỗi trường file")]
        public string nvPass { get; set; }
        public string Skyper { get; set; }
        public int PhanQuyen { get; set; }
        public Nullable<bool> DuyetKHDH { get; set; }
        public Nullable<bool> DuyetDDH { get; set; }
        public Nullable<bool> LamDDH { get; set; }
        public Nullable<bool> LamKHDH { get; set; }
        public Nullable<bool> LamGCN { get; set; }
        public Nullable<bool> LamDDHGCN { get; set; }
        public Nullable<bool> DuyetDDHGCN { get; set; }
        public string MaNV { get; set; }
        public Nullable<int> ToGiaCong { get; set; }
        public string GhiChuTongGiaCong { get; set; }
        public Nullable<bool> DuyetLai { get; set; }
        public string DoiGiaCong { get; set; }
        public Nullable<int> LapKHGCX { get; set; }
        public string PhongBan { get; set; }
        public Nullable<int> KeHoachTongQuat { get; set; }
        public string GhiChuKeHoachTongQuat { get; set; }
        public Nullable<bool> DuyetTanPhoi { get; set; }
        public Nullable<bool> DuyetTanMay { get; set; }
        public Nullable<bool> DuyetTanKho { get; set; }
        public Nullable<bool> DuyetGCX { get; set; }
        public Nullable<bool> DuyetGCN { get; set; }
        public Nullable<int> DuyetPYCDatHang { get; set; }
        public Nullable<bool> DuyetKTCN { get; set; }
        public Nullable<bool> DuyetALL { get; set; }
        public string KHHD { get; set; }
        public Nullable<int> CQDMTenChuan { get; set; }
        public string LoginErrorMgs { get; set; }
    }
}
