//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class khovatEntities : DbContext
    {
        public khovatEntities()
            : base("name=khovatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CauHinh> CauHinhs { get; set; }
        public DbSet<GCX_BaoCao> GCX_BaoCao { get; set; }
        public DbSet<GCX_DM_ThietBi> GCX_DM_ThietBi { get; set; }
        public DbSet<GCX_DonGiaGD> GCX_DonGiaGD { get; set; }
        public DbSet<GCX_DungCuGiaCong> GCX_DungCuGiaCong { get; set; }
        public DbSet<GCX_Luu_YeuCauGCN> GCX_Luu_YeuCauGCN { get; set; }
        public DbSet<GCX_NhanVienDieuKhien> GCX_NhanVienDieuKhien { get; set; }
        public DbSet<GCX_TienDoGiaCongXuong> GCX_TienDoGiaCongXuong { get; set; }
        public DbSet<GCX_TienDoGiaCongXuong_ChiTiet> GCX_TienDoGiaCongXuong_ChiTiet { get; set; }
        public DbSet<GCX_TienDoGiaCongXuong_CTGiaCong> GCX_TienDoGiaCongXuong_CTGiaCong { get; set; }
        public DbSet<GCX_TienDoGiaCongXuong_DMChuan> GCX_TienDoGiaCongXuong_DMChuan { get; set; }
        public DbSet<GCX_TienDoGiaCongXuong_Tong> GCX_TienDoGiaCongXuong_Tong { get; set; }
        public DbSet<GCX_TienDoGiaCongXuong_XuatKho> GCX_TienDoGiaCongXuong_XuatKho { get; set; }
    }
}
