//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCX_DonGiaGD
    {
        public int IDDonGia { get; set; }
        public string CongDoanGC { get; set; }
        public string MaCD { get; set; }
        public string MaNhom { get; set; }
        public string MaHangMuc { get; set; }
        public string TenHangMuc { get; set; }
        public string DKN { get; set; }
        public string DKT { get; set; }
        public string DAI { get; set; }
        public string Dai2 { get; set; }
        public string Rong2 { get; set; }
        public string Day2 { get; set; }
        public string DVT { get; set; }
        public string Hieu { get; set; }
        public string VatLieu { get; set; }
        public Nullable<double> DonGiaGC { get; set; }
    }
}
