//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCX_DungCuGiaCong
    {
        public int STTDCGC { get; set; }
        public string MaHangMuc { get; set; }
        public string TenHangMuc { get; set; }
        public string DKN { get; set; }
        public string DKT { get; set; }
        public string DAI { get; set; }
        public string Dai2 { get; set; }
        public string Rong2 { get; set; }
        public string Day2 { get; set; }
        public string DVT { get; set; }
        public string Hieu { get; set; }
        public string VatLieu { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<double> KhoiLuong1cai { get; set; }
        public Nullable<double> KhoiLuongtong { get; set; }
        public Nullable<int> STTTB { get; set; }
        public string TrangThai { get; set; }
        public Nullable<double> XuatDG { get; set; }
        public Nullable<double> TienVAT { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
    }
}
