//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCX_TienDoGiaCongXuong_XuatKho
    {
        public int IDXuatKho { get; set; }
        public string GUIDCTY { get; set; }
        public Nullable<int> IDPhieu { get; set; }
        public Nullable<int> IDPhieuXuat { get; set; }
        public string SoPhieuXuat { get; set; }
        public string DK1No { get; set; }
        public string DK1Co { get; set; }
        public string DK2No { get; set; }
        public string DK2Co { get; set; }
        public Nullable<int> IDHangMuc { get; set; }
        public string MaHangMuc { get; set; }
        public string TenHangMuc { get; set; }
        public string KT1DKN { get; set; }
        public string KT1DKT { get; set; }
        public string KT1DAI { get; set; }
        public string KT2DKN { get; set; }
        public string KT2DKT { get; set; }
        public string KT2DAI { get; set; }
        public Nullable<int> IDDVT { get; set; }
        public string TenDVT { get; set; }
        public string VatLieu { get; set; }
        public string Hieu { get; set; }
        public Nullable<decimal> TonSL { get; set; }
        public Nullable<decimal> TonKL { get; set; }
        public Nullable<decimal> XuatSL { get; set; }
        public Nullable<decimal> XuatKL { get; set; }
        public Nullable<decimal> XuatDG { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<decimal> DaNhapSL { get; set; }
        public Nullable<decimal> DaNhapKL { get; set; }
        public string CumHangMuc { get; set; }
        public string MaNhomHangMuc { get; set; }
        public string TenNhomHangMuc { get; set; }
        public Nullable<decimal> TonDPSL { get; set; }
        public Nullable<decimal> TonDPKL { get; set; }
        public Nullable<decimal> XuatDPSL { get; set; }
        public Nullable<decimal> XuatDPKL { get; set; }
        public Nullable<System.DateTime> NgayDKHT { get; set; }
        public int IDPhanHoi { get; set; }
    }
}
