//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCX_TienDoGiaCongXuong_DMChuan
    {
        public int IDPhanHoi { get; set; }
        public string MaHangMuc { get; set; }
        public string TenHangMuc { get; set; }
        public string DKN { get; set; }
        public string DKT { get; set; }
        public string DAI { get; set; }
        public string Dai2 { get; set; }
        public string Rong2 { get; set; }
        public string Day2 { get; set; }
        public string DVT { get; set; }
        public string Hieu { get; set; }
        public string VatLieu { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<double> KhoiLuong1cai { get; set; }
        public Nullable<double> KhoiLuongtong { get; set; }
        public Nullable<bool> TanDungPhoi { get; set; }
        public Nullable<bool> TanDungKho { get; set; }
        public Nullable<bool> TanDungMay { get; set; }
        public Nullable<bool> DatHang { get; set; }
        public Nullable<bool> GiaCong { get; set; }
        public Nullable<bool> GiaCongNgoai { get; set; }
        public string MaMay { get; set; }
        public string TenMay { get; set; }
        public string MaMayGCTC { get; set; }
        public string TenMayGCTC { get; set; }
        public string SoGioTC { get; set; }
        public string DonGiaTC { get; set; }
        public string MaMayGCTCNC { get; set; }
        public string TenMayGCTCNC { get; set; }
        public string SoGioTCNC { get; set; }
        public string DonGiaTCNC { get; set; }
        public string MaMayGCPC { get; set; }
        public string TenMayGCPC { get; set; }
        public string SoGioPC { get; set; }
        public string DonGiaPC { get; set; }
        public string MaMayGCPCNC { get; set; }
        public string TenMayGCPCNC { get; set; }
        public string SoGioPCNC { get; set; }
        public string DonGiaPCNC { get; set; }
        public string MaMayGCBao { get; set; }
        public string TenMayGCBao { get; set; }
        public string SoGioBao { get; set; }
        public string DonGiaBao { get; set; }
        public string MaMayGCCD { get; set; }
        public string TenMayGCCD { get; set; }
        public string SoGioCD { get; set; }
        public string DonGiaCD { get; set; }
        public string MaMayGCKhoan { get; set; }
        public string TenMayGCKhoan { get; set; }
        public string SoGioKhoan { get; set; }
        public string DonGiaKhoan { get; set; }
        public string NVTC { get; set; }
        public string NVTCNC { get; set; }
        public string NVPC { get; set; }
        public string NVPCNC { get; set; }
        public string NVBao { get; set; }
        public string NVCD { get; set; }
        public string NVKhoan { get; set; }
        public string MaMayTCTT { get; set; }
        public string MaMayTCNCTT { get; set; }
        public string MaMayPCTT { get; set; }
        public string MaMayPCNCTT { get; set; }
        public string MaMayBaoTT { get; set; }
        public string MaMayCDTT { get; set; }
        public string MaMayKhoanTT { get; set; }
        public string SoGioTCTT { get; set; }
        public string SoGioTCNCTT { get; set; }
        public string SoGioPCTT { get; set; }
        public string SoGioPCNCTT { get; set; }
        public string SoGioBaoTT { get; set; }
        public string SoGioCDTT { get; set; }
        public string SoGioKhoanTT { get; set; }
        public string MaMayGCChan { get; set; }
        public string TenMayGCChan { get; set; }
        public string SoGioChan { get; set; }
        public string DonGiaChan { get; set; }
        public string NVChan { get; set; }
        public string MaMayChanTT { get; set; }
        public string SoGioChanTT { get; set; }
        public string SoGioTCCa { get; set; }
        public string SoGioTCNCCa { get; set; }
        public string SoGioPCCa { get; set; }
        public string SoGioPCNCCa { get; set; }
        public string SoGioKhoanCa { get; set; }
        public string SoGioCDCa { get; set; }
        public string SoGioBaoCa { get; set; }
        public string SoGioChanCa { get; set; }
        public string SoCaTC { get; set; }
        public string SoCaTCNC { get; set; }
        public string SoCaPC { get; set; }
        public string SoCaPCNC { get; set; }
        public string SoCaKhoan { get; set; }
        public string SoCaCD { get; set; }
        public string SoCaBao { get; set; }
        public string SoCaChan { get; set; }
        public string MaMayGCMai { get; set; }
        public string TenMayGCMai { get; set; }
        public string SoGioMai { get; set; }
        public Nullable<double> SoLuongMai { get; set; }
        public Nullable<double> SoLuongCLMai { get; set; }
        public string GhiChuMai { get; set; }
        public string DonGiaMai { get; set; }
        public string ThanhTienMai { get; set; }
        public Nullable<bool> Co9 { get; set; }
        public string NVMai { get; set; }
        public string MaMayMaiTT { get; set; }
        public string TenMayMaiTT { get; set; }
        public string SoGioMaiTT { get; set; }
        public Nullable<decimal> SoGioMaiCa { get; set; }
        public Nullable<decimal> SoCaMai { get; set; }
    }
}
