//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCX_NhanVienDieuKhien
    {
        public int STTNhanVien { get; set; }
        public string Tenuser { get; set; }
        public string nvUser { get; set; }
        public string nvDiaChi { get; set; }
        public string nvDienThoai { get; set; }
        public string nvEmail { get; set; }
        public string MaNV { get; set; }
        public string GhiChuTongGiaCong { get; set; }
        public string DoiGiaCong { get; set; }
        public Nullable<int> STTTB { get; set; }
        public string ChucVu { get; set; }
        public string MaCauHinh { get; set; }
    }
}
