//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCX_DM_ThietBi
    {
        public string MaMayGC { get; set; }
        public string TenThietBiGC { get; set; }
        public Nullable<int> CoChucNang { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> MaCauHinh { get; set; }
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public Nullable<System.DateTime> NgayNhapTB { get; set; }
        public string NamSX { get; set; }
        public string NuocSX { get; set; }
        public string ThongSo { get; set; }
        public int STT { get; set; }
        public string TinhNang { get; set; }
        public string ViTriDatCho { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> GiaCaMay { get; set; }
        public Nullable<bool> CoLoad { get; set; }
    }
}
