//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCX_TienDoGiaCongXuong_ChiTiet
    {
        public int STT { get; set; }
        public string MaMayGC { get; set; }
        public string TenMayGC { get; set; }
        public string SoGio { get; set; }
        public Nullable<System.DateTime> NgayHoanThanh { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public Nullable<decimal> SoLuongCL { get; set; }
        public string GhiChu { get; set; }
        public string DonGia { get; set; }
        public string ThanhTien { get; set; }
        public string NV { get; set; }
        public string MaMayTT { get; set; }
        public string TenMayTT { get; set; }
        public Nullable<decimal> SoGioTT { get; set; }
        public Nullable<decimal> SoGioCa { get; set; }
        public Nullable<decimal> SoCa { get; set; }
        public Nullable<int> IDPhanHoi { get; set; }
        public Nullable<int> STTGiaCong { get; set; }
        public string TinhTrangDuyetVatTu { get; set; }
        public string NguoiLapVatTu { get; set; }
        public string CoGC { get; set; }
    }
}
