//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCX_TienDoGiaCongXuong_CTGiaCong
    {
        public int IDChiTietGC { get; set; }
        public int IDPhanHoi { get; set; }
        public string MaMayGCDK { get; set; }
        public string TenMayGCDK { get; set; }
        public Nullable<decimal> SoGioGCDK { get; set; }
        public Nullable<System.DateTime> NgayHoanThanhGCDuKien { get; set; }
        public Nullable<decimal> SoLuongCLGC { get; set; }
        public string CTGCong { get; set; }
        public string KTGCong { get; set; }
        public string TinhTrangGiaCong { get; set; }
        public Nullable<System.DateTime> NgayXuatKho { get; set; }
        public string SoPhieuXuat { get; set; }
        public Nullable<int> ID { get; set; }
        public string NguoiLapVatTu { get; set; }
        public Nullable<System.DateTime> NgayLapVatTu { get; set; }
        public string NguoiLapToGiaCong { get; set; }
        public Nullable<System.DateTime> NgayLapToGiaCong { get; set; }
        public string NguoiLapVTHT { get; set; }
        public Nullable<System.DateTime> NgayLapVTHT { get; set; }
        public string GhiChuGC { get; set; }
        public Nullable<decimal> SoLuongGCTT { get; set; }
        public string MaMayGCTT { get; set; }
        public Nullable<decimal> SoGioGCTT { get; set; }
        public Nullable<System.DateTime> NgayHoanThanhGCTT { get; set; }
        public Nullable<decimal> DonGiaGC { get; set; }
        public Nullable<decimal> ThanhTienGC { get; set; }
        public string NVGiaCong { get; set; }
        public Nullable<decimal> SoCaMayMotGio { get; set; }
        public Nullable<int> MaNVGiaCong { get; set; }
        public string CDGC { get; set; }
        public Nullable<int> CoChucNang { get; set; }
    }
}
