//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCX_Luu_YeuCauGCN
    {
        public int IDPhanHoiGCN { get; set; }
        public string MaHangMuc { get; set; }
        public string TenHangMuc { get; set; }
        public string DKN { get; set; }
        public string DKT { get; set; }
        public string DAI { get; set; }
        public string Dai2 { get; set; }
        public string Rong2 { get; set; }
        public string Day2 { get; set; }
        public string DVT { get; set; }
        public string Hieu { get; set; }
        public string VatLieu { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<double> KhoiLuong1cai { get; set; }
        public Nullable<double> KhoiLuongtong { get; set; }
        public Nullable<bool> TanDungPhoi { get; set; }
        public Nullable<bool> TanDungKho { get; set; }
        public Nullable<bool> TanDungMay { get; set; }
        public Nullable<bool> DatHang { get; set; }
        public Nullable<bool> GiaCong { get; set; }
        public Nullable<bool> GiaCongNgoai { get; set; }
        public string MaMay { get; set; }
        public string TenMay { get; set; }
        public string NguoiYCChuyenGC { get; set; }
        public Nullable<System.DateTime> NgayYCChuyenGC { get; set; }
        public Nullable<bool> ChuyenGCN { get; set; }
        public string LyDoChuyen { get; set; }
        public string DuyetChuyenGiaCong { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<int> IDPhanHoi { get; set; }
    }
}
