//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCX_TienDoGiaCongXuong_Tong
    {
        public int IDPhanHoi { get; set; }
        public string MaHangMuc { get; set; }
        public string TenHangMuc { get; set; }
        public string DKN { get; set; }
        public string DKT { get; set; }
        public string DAI { get; set; }
        public string Dai2 { get; set; }
        public string Rong2 { get; set; }
        public string Day2 { get; set; }
        public string DVT { get; set; }
        public string Hieu { get; set; }
        public string VatLieu { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<double> KhoiLuong1cai { get; set; }
        public Nullable<double> KhoiLuongtong { get; set; }
        public Nullable<bool> TanDungPhoi { get; set; }
        public Nullable<bool> TanDungKho { get; set; }
        public Nullable<bool> TanDungMay { get; set; }
        public Nullable<bool> DatHang { get; set; }
        public Nullable<bool> GiaCong { get; set; }
        public Nullable<bool> GiaCongNgoai { get; set; }
        public string MaMay { get; set; }
        public string TenMay { get; set; }
        public string ChuanLoaiGiaCong { get; set; }
        public string NguoiYCChuyenGC { get; set; }
        public Nullable<System.DateTime> NgayYCChuyenGC { get; set; }
        public Nullable<bool> ChuyenGCN { get; set; }
        public string LyDoChuyen { get; set; }
        public string DuyetChuyenGiaCong { get; set; }
        public Nullable<System.DateTime> NgayYeuCauPhoiTanDung { get; set; }
        public Nullable<System.DateTime> NgayGiaoPhoiDuKien { get; set; }
        public Nullable<System.DateTime> NgayPhoiNhapKho { get; set; }
        public Nullable<System.DateTime> NgayXuatPhoiDiGC { get; set; }
        public Nullable<System.DateTime> NgayHoanThanhDuKien { get; set; }
        public Nullable<double> SoLuongHTThucTe { get; set; }
        public Nullable<System.DateTime> NgayHoanTTTT { get; set; }
        public string ThanhTienHoanThanh { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<int> STTLGCX { get; set; }
        public string PhanhoiGiaCongTo { get; set; }
        public string NguoiPhanHoi { get; set; }
        public string TinhTrangDuyetVatTu { get; set; }
        public string TinhTrangNgayVatTu { get; set; }
        public string TinhTrangHoanThanhTo { get; set; }
        public Nullable<System.DateTime> NgayLapGCX { get; set; }
        public string NguoiLapVatTu { get; set; }
        public string NguoiLapNgayVatTu { get; set; }
        public string NguoiLapVTHT { get; set; }
        public Nullable<int> STTHMChonSuaChua { get; set; }
        public string CoChinhSua { get; set; }
        public Nullable<int> ID { get; set; }
        public string SoPhieu { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public string MaHMCu { get; set; }
        public Nullable<bool> CheckNew { get; set; }
        public string XacNhanLayHangMucNhapKho { get; set; }
        public Nullable<System.DateTime> NgayXacNhanLayHangMucNhapKho { get; set; }
        public string CoLUU { get; set; }
        public string SoPhieuYeu { get; set; }
        public string NguoiYeuCau { get; set; }
    }
}
