//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCX_BaoCao
    {
        public int STT { get; set; }
        public string ToGiaCong { get; set; }
        public string SL0117 { get; set; }
        public string DonGia0117 { get; set; }
        public string ThanhTien0117 { get; set; }
        public string SL0217 { get; set; }
        public string DonGia0217 { get; set; }
        public string ThanhTien0217 { get; set; }
        public string SL0317 { get; set; }
        public string DonGia0317 { get; set; }
        public string ThanhTien0317 { get; set; }
        public string SL0417 { get; set; }
        public string DonGia0417 { get; set; }
        public string ThanhTien0417 { get; set; }
        public string SL0517 { get; set; }
        public string DonGia0517 { get; set; }
        public string ThanhTien0517 { get; set; }
        public string SL0617 { get; set; }
        public string DonGia0617 { get; set; }
        public string ThanhTien0617 { get; set; }
        public string SL0717 { get; set; }
        public string DonGia0717 { get; set; }
        public string ThanhTien0717 { get; set; }
        public string SL0817 { get; set; }
        public string DonGia0817 { get; set; }
        public string ThanhTien0817 { get; set; }
        public string SL0917 { get; set; }
        public string DonGia0917 { get; set; }
        public string ThanhTien0917 { get; set; }
        public string SL1017 { get; set; }
        public string DonGia1017 { get; set; }
        public string ThanhTien1017 { get; set; }
        public string SL1117 { get; set; }
        public string DonGia1117 { get; set; }
        public string ThanhTien1117 { get; set; }
        public string SL1217 { get; set; }
        public string DonGia1217 { get; set; }
        public string ThanhTien1217 { get; set; }
        public string SL2017 { get; set; }
        public string ThanhTien2017 { get; set; }
        public string SL0118 { get; set; }
        public string DonGia0118 { get; set; }
        public string ThanhTien0118 { get; set; }
        public string SL0218 { get; set; }
        public string DonGia0218 { get; set; }
        public string ThanhTien0218 { get; set; }
        public string SL0318 { get; set; }
        public string DonGia0318 { get; set; }
        public string ThanhTien0318 { get; set; }
        public string SL0418 { get; set; }
        public string DonGia0418 { get; set; }
        public string ThanhTien0418 { get; set; }
        public string SL0518 { get; set; }
        public string DonGia0518 { get; set; }
        public string ThanhTien0518 { get; set; }
        public string SL0618 { get; set; }
        public string DonGia0618 { get; set; }
        public string ThanhTien0618 { get; set; }
        public string SL0718 { get; set; }
        public string DonGia0718 { get; set; }
        public string ThanhTien0718 { get; set; }
        public string SL0818 { get; set; }
        public string DonGia0818 { get; set; }
        public string ThanhTien0818 { get; set; }
        public string SL0918 { get; set; }
        public string DonGia0918 { get; set; }
        public string ThanhTien0918 { get; set; }
        public string SL1018 { get; set; }
        public string DonGia1018 { get; set; }
        public string ThanhTien1018 { get; set; }
        public string SL1118 { get; set; }
        public string DonGia1118 { get; set; }
        public string ThanhTien1118 { get; set; }
        public string SL1218 { get; set; }
        public string DonGia1218 { get; set; }
        public string ThanhTien1218 { get; set; }
        public string SL2018 { get; set; }
        public string ThanhTien2018 { get; set; }
        public string SL0119 { get; set; }
        public string DonGia0119 { get; set; }
        public string ThanhTien0119 { get; set; }
        public string SL0219 { get; set; }
        public string DonGia0219 { get; set; }
        public string ThanhTien0219 { get; set; }
        public string SL0319 { get; set; }
        public string DonGia0319 { get; set; }
        public string ThanhTien0319 { get; set; }
        public string SL0419 { get; set; }
        public string DonGia0419 { get; set; }
        public string ThanhTien0419 { get; set; }
        public string SL0519 { get; set; }
        public string DonGia0519 { get; set; }
        public string ThanhTien0519 { get; set; }
        public string SL0619 { get; set; }
        public string DonGia0619 { get; set; }
        public string ThanhTien0619 { get; set; }
        public string SL0719 { get; set; }
        public string DonGia0719 { get; set; }
        public string ThanhTien0719 { get; set; }
        public string SL0819 { get; set; }
        public string DonGia0819 { get; set; }
        public string ThanhTien0819 { get; set; }
        public string SL0919 { get; set; }
        public string DonGia0919 { get; set; }
        public string ThanhTien0919 { get; set; }
        public string SL1019 { get; set; }
        public string DonGia1019 { get; set; }
        public string ThanhTien1019 { get; set; }
        public string SL1119 { get; set; }
        public string DonGia1119 { get; set; }
        public string ThanhTien1119 { get; set; }
        public string SL1219 { get; set; }
        public string DonGia1219 { get; set; }
        public string ThanhTien1219 { get; set; }
        public string SL2019 { get; set; }
        public string ThanhTien2019 { get; set; }
        public string SL0120 { get; set; }
        public string DonGia0120 { get; set; }
        public string ThanhTien0120 { get; set; }
        public string SL0220 { get; set; }
        public string DonGia0220 { get; set; }
        public string ThanhTien0220 { get; set; }
        public string SL0320 { get; set; }
        public string DonGia0320 { get; set; }
        public string ThanhTien0320 { get; set; }
        public string SL0420 { get; set; }
        public string DonGia0420 { get; set; }
        public string ThanhTien0420 { get; set; }
        public string SL0520 { get; set; }
        public string DonGia0520 { get; set; }
        public string ThanhTien0520 { get; set; }
        public string SL0620 { get; set; }
        public string DonGia0620 { get; set; }
        public string ThanhTien0620 { get; set; }
        public string SL0720 { get; set; }
        public string DonGia0720 { get; set; }
        public string ThanhTien0720 { get; set; }
        public string SL0820 { get; set; }
        public string DonGia0820 { get; set; }
        public string ThanhTien0820 { get; set; }
        public string SL0920 { get; set; }
        public string DonGia0920 { get; set; }
        public string ThanhTien0920 { get; set; }
        public string SL1020 { get; set; }
        public string DonGia1020 { get; set; }
        public string ThanhTien1020 { get; set; }
        public string SL1120 { get; set; }
        public string DonGia1120 { get; set; }
        public string ThanhTien1120 { get; set; }
        public string SL1220 { get; set; }
        public string DonGia1220 { get; set; }
        public string ThanhTien1220 { get; set; }
        public string SL2020 { get; set; }
        public string ThanhTien2020 { get; set; }
    }
}
